url: http://127.0.0.1:8888
spring:
  datasource:
    url: jdbc:mysql://192.168.1.127:3306/dev_hzy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: 51BJhzy.c@m
    driver-class-name: com.mysql.jdbc.Driver