spring:
  profiles:
   active: dev
server:
  port: 8888

mybatis:
  mapperLocations: classpath:/mapper/*Mapper.xml
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#logging.config=classpath:log4j2-dev.xml
#url=http://localhost:8888

#url=https://www.51bjhzy.com